// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAElkegFTTHmizRiTtkAcCs2tSbpFweaew',
    appId: '1:882972371329:web:c34721c2e65aeeb2f1e080',
    messagingSenderId: '882972371329',
    projectId: 'zoom-clone-22c97',
    authDomain: 'zoom-clone-22c97.firebaseapp.com',
    storageBucket: 'zoom-clone-22c97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuop00iEp3sXsPES91Km3n5rIDuc64E0',
    appId: '1:882972371329:android:cdcf7110aa17d22af1e080',
    messagingSenderId: '882972371329',
    projectId: 'zoom-clone-22c97',
    storageBucket: 'zoom-clone-22c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdCIlb0Obvm8ZfdzjNr1NymYPu_g_ESY',
    appId: '1:882972371329:ios:cb3891a04d85c448f1e080',
    messagingSenderId: '882972371329',
    projectId: 'zoom-clone-22c97',
    storageBucket: 'zoom-clone-22c97.appspot.com',
    iosClientId: '882972371329-09onbovem3nq7mfktfg6vmht97ksico9.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZdCIlb0Obvm8ZfdzjNr1NymYPu_g_ESY',
    appId: '1:882972371329:ios:cb3891a04d85c448f1e080',
    messagingSenderId: '882972371329',
    projectId: 'zoom-clone-22c97',
    storageBucket: 'zoom-clone-22c97.appspot.com',
    iosClientId: '882972371329-09onbovem3nq7mfktfg6vmht97ksico9.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
